services:
  redis-database:
    image: redis
    restart: always
    container_name: mailstorage-redis
    command: >
      --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  redis_data:
    external: false
