services:
  app:
    image: app
    build: docker/app
    command: bash -c "yarn && yarn dev"
    container_name: mailstorage
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis-database

  redis-database:
    image: redis
    restart: always
    container_name: mailstorage-redis
    command: >
      --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  redis_data:
    external: false
