name: Node Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  backend_test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.17.0
      - run: npm --prefix backend ci
      - run: npm --prefix backend test --run-in-band --verbose
      - run: npm --prefix backend build
