name: Node Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  backend_test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/test.yaml
      - run: yarn --cwd backend build
